# Numpy...

In [1]:
# numpy numerical python...
import numpy as np


In [2]:
# convert list into array
Di=np.array([10,20,30,40])
ti=np.array([5,10,15,20])
si=Di//ti
print(si)
print(type(si))

[2 2 2 2]
<class 'numpy.ndarray'>


In [3]:
# diff b\w list and array...
# nd no. of dimension

In [4]:
# methods
a=np.array([1,2,3,4])
print(type(a))
print(a.ndim) #no. of dimension
print(a.size) #size of array
print(a.dtype) # type of array
print(a.shape) # it only return elements can't give rows and coloum...

<class 'numpy.ndarray'>
1
4
int32
(4,)


In [5]:
a=np.array([[1.2,3.2,6],[1.1,2,1.3],[2,3.2,2.2],[1,2,3]])
print(a)
print(type(a))
print(a.ndim) #dimension
print(a.dtype) #give prefrence to float..
print(a.size) #no. of elements
print(len(a)) # no. of rows
print(a.shape) #rows,coloum 

[[1.2 3.2 6. ]
 [1.1 2.  1.3]
 [2.  3.2 2.2]
 [1.  2.  3. ]]
<class 'numpy.ndarray'>
2
float64
12
4
(4, 3)


In [6]:
a=np.array([[[[[[1],[4],[7]]]]]])
print(a)
print(a.shape)

[[[[[[1]
     [4]
     [7]]]]]]
(1, 1, 1, 1, 3, 1)


In [48]:
a=np.array([[[1],[1],[1]],[[2],[2],[2]],[[3],[3],[3]]])
print(a)
print(a.shape)

[[[1]
  [1]
  [1]]

 [[2]
  [2]
  [2]]

 [[3]
  [3]
  [3]]]
(3, 3, 1)


In [8]:
# condition on array
marks=np.array([[44,55,66,77,88,99],[44,65,78,66,45,99]])
passing_marks=50
marks>passing_marks

array([[False,  True,  True,  True,  True,  True],
       [False,  True,  True,  True, False,  True]])

In [9]:
a=marks[marks>passing_marks]
print(a)

[55 66 77 88 99 65 78 66 99]


In [10]:
# Shallow copy and deep copy

In [11]:
B=np.array([['Agra','Aligarh','kanpur'],["lucknow",'brailey','mirzapur']])
C=B
print(C)
print(B)

[['Agra' 'Aligarh' 'kanpur']
 ['lucknow' 'brailey' 'mirzapur']]
[['Agra' 'Aligarh' 'kanpur']
 ['lucknow' 'brailey' 'mirzapur']]


In [12]:
# shallow copy it can change orignal array
C[1][1]="Delhi"
print(C)

[['Agra' 'Aligarh' 'kanpur']
 ['lucknow' 'Delhi' 'mirzapur']]


In [13]:
print(B)

[['Agra' 'Aligarh' 'kanpur']
 ['lucknow' 'Delhi' 'mirzapur']]


In [14]:
A=np.array([['Agra','Aligarh','kanpur'],["lucknow",'brailey','mirzapur']])
D=A.copy()
print(A)
print(D)

[['Agra' 'Aligarh' 'kanpur']
 ['lucknow' 'brailey' 'mirzapur']]
[['Agra' 'Aligarh' 'kanpur']
 ['lucknow' 'brailey' 'mirzapur']]


In [15]:
# deep copy it can't change orignal array
D[1][1]="Delhi"
print(D)

[['Agra' 'Aligarh' 'kanpur']
 ['lucknow' 'Delhi' 'mirzapur']]


In [16]:
print(A)

[['Agra' 'Aligarh' 'kanpur']
 ['lucknow' 'brailey' 'mirzapur']]


In [17]:
# Mathematical 

In [18]:
a=np.array([[1,2,3]])
np.sqrt(a)


array([[1.        , 1.41421356, 1.73205081]])

In [19]:
# shape manipulation

In [20]:
x=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(x.shape)

(2, 6)


In [21]:
print(x.reshape(12,1))# reshape can't change orignal array
print(x.reshape(1,12))
print(x.reshape(3,4))
print(x.reshape(4,3))
print(x.reshape(2,6))
print(x.reshape(6,2))
# orignal array
print(x)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [22]:
x.resize(3,4)# resize change the orignal array

In [23]:
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [24]:
# ravel:it change multi dimension array into 1 d array
Z=x.ravel()
print(Z.ndim)
print(x)

1
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
a=np.array([[[[101,102,103,104,105],[106,107,108,109,110],[1,2,3,4,5]]]])
print(a.ndim)
b=a.ravel()
print(b)
# orignal array has  change
print(a)

4
[101 102 103 104 105 106 107 108 109 110   1   2   3   4   5]
[[[[101 102 103 104 105]
   [106 107 108 109 110]
   [  1   2   3   4   5]]]]


In [26]:
a

array([[[[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [  1,   2,   3,   4,   5]]]])

In [27]:
b

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110,   1,   2,   3,
         4,   5])

In [28]:
b[0]=100

In [29]:
b

array([100, 102, 103, 104, 105, 106, 107, 108, 109, 110,   1,   2,   3,
         4,   5])

In [30]:
a

array([[[[100, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [  1,   2,   3,   4,   5]]]])

In [31]:
# flatten() can't change orignal array
a=np.array([[[[101,102,103,104,105],[106,107,108,109,110],[1,2,3,4,5]]]])
print(a.ndim)
b=a.flatten()

4


In [32]:
b

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110,   1,   2,   3,
         4,   5])

In [33]:
b[0]=50

In [34]:
b

array([ 50, 102, 103, 104, 105, 106, 107, 108, 109, 110,   1,   2,   3,
         4,   5])

In [35]:
a

array([[[[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [  1,   2,   3,   4,   5]]]])

# Broadcasting

In [2]:
import numpy as np

a=np.array([[[[ [[1,2,3,4],[1,2,3,4]] , [[1,2,3,4],[1,2,3,4]] ]]]])
print(a.ndim)
print(a.shape)
print(a.size)
print(a)

6
(1, 1, 1, 2, 2, 4)
16
[[[[[[1 2 3 4]
     [1 2 3 4]]

    [[1 2 3 4]
     [1 2 3 4]]]]]]


In [36]:
# ndim

In [37]:
x=np.array([[[1,2,3,4],[5,6,7,8]]],ndmin=5)
x

array([[[[[1, 2, 3, 4],
          [5, 6, 7, 8]]]]])

In [38]:
ARR=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(ARR.shape)
print(ARR)


(4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [39]:
print(ARR.sum(axis=0)) #rows
print(ARR.sum(axis=1)) #coloum

[22 26 30]
[ 6 15 24 33]


In [40]:
ARR.T  #T is for tanspose.....

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [41]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [42]:
b=np.linalg.inv(a)

In [43]:
b

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [8]:
# a.trace()

In [2]:
import numpy as np

In [6]:
# matrix
# matrix only be in Two dimension can't be one and single dimension...
x=np.mat([[10,9,8],[7,6,8],[4,3,2]])
y=np.mat([[10,9,8],[7,6,8],[4,3,2]])
print(type(x))
print(x*y)

<class 'numpy.matrix'>
[[195 168 168]
 [144 123 120]
 [ 69  60  60]]


# nuumpy.fromfunction

In [10]:
np.fromfunction(lambda i,j:i+j,(3,3)) #by default float type hota h

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [11]:
np.fromfunction(lambda i,j:i*j,(4,4), dtype=int) #dtype=int chaiye

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [14]:
np.fromfunction(lambda i,j:i>j,(4,4))

array([[False, False, False, False],
       [ True, False, False, False],
       [ True,  True, False, False],
       [ True,  True,  True, False]])

# arange and linespacce

In [16]:
np.arange(1,11) # print 1 to 10 in array 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [1]:
# data norml distribution  h ki nhi